-- ============================================================================
-- superi.ge — ბრენდები: დუბლიკატების გაერთიანება, სუფთა მისამართები,
-- სათაური და აღწერა ყველა ბრენდის გვერდს (Google-ის მოთხოვნებით).
-- 1) Blackview (22 პროდ., ლოგოს გარეშე) → BLACKVIEW (ლოგოთი)
--    Nothing (2 პროდ., ლოგოს გარეშე)  → NOTHING PHONE (ლოგოთი და აღწერით)
--    პროდუქტები გადადის დარჩენილ ბრენდზე, ძველი მისამართი 301-ით გადამისამართდება.
-- 2) Keter და Rattan იღებენ სუფთა მისამართს (/keter/, /rattan/) -ka-ს ნაცვლად.
-- 3) ყველა ბრენდს: სათაური „[ბრენდი] — საუკეთესო ფასები | Superi.ge“ და აღწერა.
-- ცვლილებამდე წაშლილი ჩანაწერების ასლი ინახება superi_bk_* ცხრილებში (დაბრუნებისთვის).
-- ============================================================================

SET NAMES utf8mb4;

-- 0) ბრენდის გვერდების SEO-ტიპის და გადამისამართების ფორმატის დადგენა
SET @et := (SELECT s.type FROM cscart_seo_names s JOIN cscart_product_feature_variant_descriptions vd ON vd.variant_id = s.object_id AND vd.lang_code = 'ka' WHERE s.name = 'samsung' AND s.lang_code = 'ka' AND vd.variant = 'SAMSUNG' LIMIT 1);
SET @f := (SELECT src FROM cscart_seo_redirects WHERE TRIM(BOTH '/' FROM src) = 'category-15' LIMIT 1);
SET @pre := IF(@f IS NULL OR LEFT(@f,1) = '/', '/', '');
SET @post := IF(@f IS NULL OR RIGHT(@f,1) = '/', '/', '');
SET @k1 := (SELECT s.object_id FROM cscart_seo_names s JOIN cscart_product_feature_variant_descriptions vd ON vd.variant_id = s.object_id AND vd.lang_code = 'ka' WHERE s.type = @et AND s.lang_code = 'ka' AND s.name = 'blackview' AND LOWER(REPLACE(vd.variant, ' ', '')) = 'blackview' LIMIT 1);
SET @d1 := (SELECT s.object_id FROM cscart_seo_names s JOIN cscart_product_feature_variant_descriptions vd ON vd.variant_id = s.object_id AND vd.lang_code = 'ka' WHERE s.type = @et AND s.lang_code = 'ka' AND s.name = 'blackview-ka' AND LOWER(REPLACE(vd.variant, ' ', '')) = 'blackview' LIMIT 1);
SET @k2 := (SELECT s.object_id FROM cscart_seo_names s JOIN cscart_product_feature_variant_descriptions vd ON vd.variant_id = s.object_id AND vd.lang_code = 'ka' WHERE s.type = @et AND s.lang_code = 'ka' AND s.name = 'nothing-phone' AND LOWER(REPLACE(vd.variant, ' ', '')) = 'nothingphone' LIMIT 1);
SET @d2 := (SELECT s.object_id FROM cscart_seo_names s JOIN cscart_product_feature_variant_descriptions vd ON vd.variant_id = s.object_id AND vd.lang_code = 'ka' WHERE s.type = @et AND s.lang_code = 'ka' AND s.name = 'nothing' AND LOWER(REPLACE(vd.variant, ' ', '')) = 'nothing' LIMIT 1);
SET @kf1 := (SELECT feature_id FROM cscart_product_feature_variants WHERE variant_id = @k1);
SET @kf2 := (SELECT feature_id FROM cscart_product_feature_variants WHERE variant_id = @k2);

-- 1) დუბლიკატების ასლი (დაბრუნებისთვის)
CREATE TABLE IF NOT EXISTS superi_bk_product_features_values AS SELECT * FROM cscart_product_features_values WHERE variant_id IN (@d1, @d2);
CREATE TABLE IF NOT EXISTS superi_bk_product_feature_variants AS SELECT * FROM cscart_product_feature_variants WHERE variant_id IN (@d1, @d2);
CREATE TABLE IF NOT EXISTS superi_bk_product_feature_variant_descriptions AS SELECT * FROM cscart_product_feature_variant_descriptions WHERE variant_id IN (@d1, @d2);
CREATE TABLE IF NOT EXISTS superi_bk_brand_seo AS SELECT * FROM cscart_seo_names WHERE type = @et AND object_id IN (@d1, @d2);

-- 1) blackview-ka → გაერთიანება
UPDATE IGNORE cscart_product_features_values SET variant_id = @k1, feature_id = @kf1 WHERE variant_id = @d1 AND @k1 IS NOT NULL AND @d1 IS NOT NULL AND @k1 <> @d1;
DELETE FROM cscart_product_features_values WHERE variant_id = @d1 AND @k1 IS NOT NULL AND @d1 IS NOT NULL AND @k1 <> @d1;
DELETE FROM cscart_product_feature_variant_descriptions WHERE variant_id = @d1 AND @k1 IS NOT NULL AND @d1 IS NOT NULL AND @k1 <> @d1;
DELETE FROM cscart_product_feature_variants WHERE variant_id = @d1 AND @k1 IS NOT NULL AND @d1 IS NOT NULL AND @k1 <> @d1;
DELETE FROM cscart_images_links WHERE object_type = 'feature_variant' AND object_id = @d1 AND @k1 IS NOT NULL AND @d1 IS NOT NULL AND @k1 <> @d1;
DELETE FROM cscart_seo_names WHERE type = @et AND object_id = @d1 AND @k1 IS NOT NULL AND @d1 IS NOT NULL AND @k1 <> @d1;
UPDATE cscart_seo_redirects SET object_id = @k1 WHERE type = @et AND object_id = @d1 AND @k1 IS NOT NULL AND @d1 IS NOT NULL AND @k1 <> @d1;
DELETE FROM cscart_seo_redirects WHERE company_id = 1 AND TRIM(BOTH '/' FROM src) = 'blackview-ka' AND @k1 IS NOT NULL AND @d1 IS NOT NULL AND @k1 <> @d1;
INSERT IGNORE INTO cscart_seo_redirects (src, type, object_id, lang_code, company_id) SELECT CONCAT(@pre, 'blackview-ka', @post), @et, @k1, 'ka', 1 FROM DUAL WHERE @k1 IS NOT NULL AND @d1 IS NOT NULL AND @k1 <> @d1;

-- 1) nothing → გაერთიანება
UPDATE IGNORE cscart_product_features_values SET variant_id = @k2, feature_id = @kf2 WHERE variant_id = @d2 AND @k2 IS NOT NULL AND @d2 IS NOT NULL AND @k2 <> @d2;
DELETE FROM cscart_product_features_values WHERE variant_id = @d2 AND @k2 IS NOT NULL AND @d2 IS NOT NULL AND @k2 <> @d2;
DELETE FROM cscart_product_feature_variant_descriptions WHERE variant_id = @d2 AND @k2 IS NOT NULL AND @d2 IS NOT NULL AND @k2 <> @d2;
DELETE FROM cscart_product_feature_variants WHERE variant_id = @d2 AND @k2 IS NOT NULL AND @d2 IS NOT NULL AND @k2 <> @d2;
DELETE FROM cscart_images_links WHERE object_type = 'feature_variant' AND object_id = @d2 AND @k2 IS NOT NULL AND @d2 IS NOT NULL AND @k2 <> @d2;
DELETE FROM cscart_seo_names WHERE type = @et AND object_id = @d2 AND @k2 IS NOT NULL AND @d2 IS NOT NULL AND @k2 <> @d2;
UPDATE cscart_seo_redirects SET object_id = @k2 WHERE type = @et AND object_id = @d2 AND @k2 IS NOT NULL AND @d2 IS NOT NULL AND @k2 <> @d2;
DELETE FROM cscart_seo_redirects WHERE company_id = 1 AND TRIM(BOTH '/' FROM src) = 'nothing' AND @k2 IS NOT NULL AND @d2 IS NOT NULL AND @k2 <> @d2;
INSERT IGNORE INTO cscart_seo_redirects (src, type, object_id, lang_code, company_id) SELECT CONCAT(@pre, 'nothing', @post), @et, @k2, 'ka', 1 FROM DUAL WHERE @k2 IS NOT NULL AND @d2 IS NOT NULL AND @k2 <> @d2;

-- 2) Keter და Rattan: პროდუქტს აღწერითი მისამართი, ბრენდს სუფთა
UPDATE cscart_seo_names SET name = 'baghis-avejis-komplekti-keter' WHERE type = 'p' AND lang_code = 'ka' AND name = 'keter' AND NOT EXISTS (SELECT 1 FROM (SELECT name FROM cscart_seo_names WHERE name = 'baghis-avejis-komplekti-keter') t);
SET @b := (SELECT object_id FROM cscart_seo_names WHERE type = @et AND lang_code = 'ka' AND name = 'keter-ka' LIMIT 1);
SET @free := (SELECT COUNT(*) FROM cscart_seo_names WHERE name = 'keter') = 0;
DELETE FROM cscart_seo_redirects WHERE company_id = 1 AND TRIM(BOTH '/' FROM src) IN ('keter-ka', 'keter') AND @b IS NOT NULL AND @free;
INSERT IGNORE INTO cscart_seo_redirects (src, type, object_id, lang_code, company_id) SELECT CONCAT(@pre, 'keter-ka', @post), @et, @b, 'ka', 1 FROM DUAL WHERE @b IS NOT NULL AND @free;
UPDATE cscart_seo_names SET name = 'keter' WHERE type = @et AND lang_code = 'ka' AND name = 'keter-ka' AND @free;

UPDATE cscart_seo_names SET name = 'naturaluri-ratanis-baghis-avejis-nakrebi' WHERE type = 'p' AND lang_code = 'ka' AND name = 'rattan' AND NOT EXISTS (SELECT 1 FROM (SELECT name FROM cscart_seo_names WHERE name = 'naturaluri-ratanis-baghis-avejis-nakrebi') t);
SET @b := (SELECT object_id FROM cscart_seo_names WHERE type = @et AND lang_code = 'ka' AND name = 'rattan-ka' LIMIT 1);
SET @free := (SELECT COUNT(*) FROM cscart_seo_names WHERE name = 'rattan') = 0;
DELETE FROM cscart_seo_redirects WHERE company_id = 1 AND TRIM(BOTH '/' FROM src) IN ('rattan-ka', 'rattan') AND @b IS NOT NULL AND @free;
INSERT IGNORE INTO cscart_seo_redirects (src, type, object_id, lang_code, company_id) SELECT CONCAT(@pre, 'rattan-ka', @post), @et, @b, 'ka', 1 FROM DUAL WHERE @b IS NOT NULL AND @free;
UPDATE cscart_seo_names SET name = 'rattan' WHERE type = @et AND lang_code = 'ka' AND name = 'rattan-ka' AND @free;

-- 3) ყველა ბრენდის სათაური და აღწერა
UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_product_feature_variants v ON v.variant_id = vd.variant_id JOIN cscart_product_features f ON f.feature_id = v.feature_id AND f.feature_type = 'E'
SET vd.page_title = CONCAT(CASE WHEN vd.variant LIKE '%|%' THEN CONCAT(TRIM(SUBSTRING_INDEX(vd.variant, '|', 1)), ' (', TRIM(SUBSTRING_INDEX(vd.variant, '|', -1)), ')') WHEN BINARY vd.variant = BINARY LOWER(vd.variant) THEN CONCAT(UPPER(LEFT(vd.variant, 1)), SUBSTRING(vd.variant, 2)) ELSE vd.variant END, ' — საუკეთესო ფასები | Superi.ge'),
    vd.meta_description = CONCAT(CASE WHEN vd.variant LIKE '%|%' THEN TRIM(SUBSTRING_INDEX(vd.variant, '|', 1)) WHEN BINARY vd.variant = BINARY LOWER(vd.variant) THEN CONCAT(UPPER(LEFT(vd.variant, 1)), SUBSTRING(vd.variant, 2)) ELSE vd.variant END, '-ის პროდუქცია Superi.ge-ზე: ✓ ნაწილ-ნაწილ გადახდა ✓ უფასო მიწოდება თბილისში 100₾-დან ✓ მიწოდება მთელ საქართველოში.')
WHERE vd.lang_code = 'ka' AND TRIM(vd.variant) <> '';

-- 4) შემოწმება
SELECT @et AS seo_type, @k1 AS blackview, @d1 AS blackview_ka, @k2 AS nothing_phone, @d2 AS nothing;
SELECT COUNT(*) AS brands, SUM(vd.page_title LIKE '% — საუკეთესო ფასები | Superi.ge') AS titles_ok, SUM(vd.meta_description LIKE '%ნაწილ-ნაწილ გადახდა%') AS descriptions_ok FROM cscart_product_feature_variant_descriptions vd JOIN cscart_product_feature_variants v ON v.variant_id = vd.variant_id JOIN cscart_product_features f ON f.feature_id = v.feature_id AND f.feature_type = 'E' WHERE vd.lang_code = 'ka';

-- ============================================================================
-- დაბრუნება (კომენტარია, არ სრულდება). ჯერ გაუშვით ხაზი SET @et ზემოდან.
-- დუბლიკატები: INSERT IGNORE INTO cscart_product_feature_variants SELECT * FROM superi_bk_product_feature_variants;
--              INSERT IGNORE INTO cscart_product_feature_variant_descriptions SELECT * FROM superi_bk_product_feature_variant_descriptions;
--              INSERT IGNORE INTO cscart_seo_names SELECT * FROM superi_bk_brand_seo;
--              UPDATE cscart_product_features_values fv JOIN superi_bk_product_features_values b ON b.product_id = fv.product_id AND b.lang_code = fv.lang_code AND b.feature_id = fv.feature_id SET fv.variant_id = b.variant_id;
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'chuwi' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'keter-ka' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'garden-star' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'home-decor' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'domino' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'crown' SET vd.page_title = 'Crown ტექნიკა | Crown-ის პროდუქცია ონლაინ Superi.ge-ზე', vd.meta_description = 'Crown-ის ტექნიკა Superi.ge-ზე — შეარჩიეთ ვენტილატორები, სამზარეულოს და საყოფაცხოვრებო მოწყობილობები საუკეთესო ფასად. შეიძინეთ Crown-ის პროდუქცია მარტივად და სწრაფად.' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'shark' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'allibert' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'koopman' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'rattan-ka' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'gigabyte-kompiuteris-natsilebi' SET vd.page_title = 'GIGABYTE - დედა დაფები, ვიდეო ბარათები და კომპიუტერის ნაწილები', vd.meta_description = 'GIGABYTE კომპიუტერის ნაწილები და აქსესუარები Superi.ge-ზე - დედა დაფები, ვიდეო ბარათები, კვების ბლოკები და სხვა ოფიციალური პროდუქცია გარანტიით და საუკეთესო ფასად.' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'amd' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'intel' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'wanbo' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'nothing' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'blackview-ka' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'dewalt-instrumentebi' SET vd.page_title = 'DEWALT ინსტრუმენტები – პროფესიონალური ელექტრო და აკუმულატორული ხელსაწყოები | DeWalt Georgia', vd.meta_description = 'DEWALT ინსტრუმენტები და ბაღის ტექნიკა – პროფესიონალური ხარისხის ელექტრო და აკუმულატორული ინსტრუმენტები, ბაღის ტექნიკა და აქსესუარები გამძლეობითა და მაღალი წარმადობით' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'tecno' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'tcl' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'beko' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'roadmarch' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'colorview' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'sanny' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'vox' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'vestel' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'midea' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'hisense' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'skytech' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'toshiba' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'lg' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'philips' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'grundig' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'skyworth' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'daewoo' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'vestfrost' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'realme' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'nokia' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'oukitel' SET vd.page_title = '', vd.meta_description = 'შეიძინე OUKITEL - ის ყველაზე გამძლე პროდუქცია სუპერ ფასად, SUPERI.GE - ზე' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'indesit' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'acer' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'asus' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'braun' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'gorenje-superi-ge' SET vd.page_title = 'gorenje | Superi.ge | ონლაინ მაღაზია', vd.meta_description = 'Gorenje: ინოვაციური ტექნოლოგიები და სტილური დიზაინი თქვენი ყოველდღიური ცხოვრებისთვის. ჩვენი მოწყობილობები უზრუნველყოფენ კომფორტს, ეფექტურობას და ენერგიის დაზოგვას, რაც იდეალური გადაწყვეტილებაა თქვენს სახლში.' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'akog' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'ersel' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'singer' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'sony' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'aeg' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'electrolux' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'hotpoint-ariston' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'google-pixel' SET vd.page_title = 'GOOGLE PIXEL', vd.meta_description = 'აღმოაჩინე GOOGLE PIXEL ის თანამედროვე და უძლიერესი სმარტფონები საუკეთესო ფასად, შეიძინე ონლაინ და მიიღე შეკვეთა იმავე დღეს.' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'motorola' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'fujifilm' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'honor' SET vd.page_title = 'HONOR', vd.meta_description = 'HONOR არის გლობალური ტექნოლოგიური ბრენდი, რომელიც სპეციალიზირებულია სმარტფონების, ტაბლეტების, ლეპტოპების და სხვა ჭკვიანი მოწყობილობების წარმოებაში. ბრენდი ცნობილია თავისი ინოვაციური დიზაინით, მაღალი ხარისხის კამერებით და მოწინავე ტექნოლოგიებით' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'korkmaz' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'berllong' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'ardesto' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'oneplus' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'zilan' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'dell' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'hp' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'hitachi' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'hyundai' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'graetz' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'oz' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'dingqi' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'panasonic' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'pro-plan' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'fakir' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'arnica' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'franko' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'karcher' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'ilife' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'lego' SET vd.page_title = 'LEGO კონსტრუქტორები ბავშვებისა და მოზრდილებისთვის – თემატური ნაკრებები საუკეთესო ფასად', vd.meta_description = 'აღმოაჩინე ორიგინალი LEGO ნაკრები ყველა ასაკისთვის — Minecraft, Technic, Friends და სხვა თემატიკით. უსაფრთხო, შემოქმედებითი და მაღალი ხარისხის კონსტრუქტორები ბავშვებისა და მოზრდილებისთვის' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'janome' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'brother' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'arshia' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'trinx' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'varta' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'lavor' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'whirlpool' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'falez' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'bauma' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'chigo' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'mitsubishi' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'aux' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'millen' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'zellmer' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'cooper-and-hunter' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'xbox' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'nintendo' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'lenovo' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'infinix' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'bestway' SET vd.page_title = 'BESTWAY კარკასული აუზები და აქსესუარები | ხარისხიანი აუზები ონლაინ', vd.meta_description = 'BESTWAY — მსოფლიოში ლიდერი კარკასული აუზებისა და ზაფხულის აქსესუარების მწარმოებელი. ხარისხიანი მასალები, ინოვაციური დიზაინი და მრავალფეროვანი არჩევანი ყველა მომხმარებლისთვის' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'intex' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'hecht' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'royal-turbo' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'manamo' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'storm' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'oppo' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'remeza' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'ingco' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'luxell' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'simfer' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'itimat' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'blaupunkt' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'haier' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'allscreen' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'ilitek' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'ninja' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'sencor' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'canon' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'reflecta' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'tp-link' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'tenda' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'epson' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'segway' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'pro-form' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'kenwood' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'ud' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'polaroid' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'autopower' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'harman-kardon' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'mayer' SET vd.page_title = 'MAYER-ის კონდიციონერები', vd.meta_description = 'MAYER-ის კონდიციონერები და სპლიტ სისტემები ონლაინ. ენერგოეფექტური მოდელები ნებისმიერი ფართისთვის. შეიძინეთ MAYER-ის ტექნიკა ოფიციალური გარანტიითა და მიწოდებით!' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'hyperx' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'dixi' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'al-ko' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'exide' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'totem' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = '2e' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'luminarc' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'toorx' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'total' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'black-and-decker' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'goodyear' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'kumtel' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'vileda' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'fujiyama' SET vd.page_title = 'FUJIYAMA | Superi.ge', vd.meta_description = 'FUJIYAMA გაზის გამათბობლები – მაღალი ხარისხი, ეფექტურობა და თანამედროვე დიზაინი. ჩვენი პროდუქტი გაწვდით მაქსიმალურ სითბოს მინიმალური გაზის მოხმარებით. შეარჩიეთ FUJIYAMA და უზრუნველყავით სასურველი კომფორტი და სითბო თქვენს სივრცეში' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'nothing-phone' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'logitech' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'hagen' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'dyson' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'byintek' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'llorens' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'tefal' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'smeg' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'blackview' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'marshall' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'dji' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'kugoo' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'konner-and-sohnen' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'ronix' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'schpindel' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'regal' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'gree' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'sharp' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'yenkee' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'delonghi' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'hoffmann' SET vd.page_title = '', vd.meta_description = 'HOFFMANN - საიმედო ელექტრო ტექნიკა თქვენი სახლისთვის: მაღალი ხარისხი, თანამედროვე დიზაინი, ხელმისაწვდომი ფასები. აღმოაჩინეთ ტექნიკა, რომელიც თქვენს ცხოვრებას გააადვილებს!' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'arzum' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'xerox' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'rowenta' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'hosseven' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'gilan' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'riken' SET vd.page_title = 'RIKEN ბრენდის საბურავები საუკეთესო ფასად | SUPERI.GE', vd.meta_description = 'SUPERI.GE გთავაზობთ RIKEN ბრენდის საბურავების ფართო არჩევანს, რომელიც აერთიანებს მდგრადობას, სანდოობას და ეფექტურობის მაღალ სტანდარტებს. მოძებნეთ იდეალური საბურავები საუკეთესო ფასად.' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'nordictrack' SET vd.page_title = 'NordicTrack სარბენი ბილიკები და ფიტნეს ტრენაჟორები | SUPERI.GE', vd.meta_description = 'შეიძინე NordicTrack-ის სარბენი ბილიკები და ფიტნეს ტრენაჟორები SUPER-ში საუკეთესო ფასად. პრემიუმ ხარისხი, კომფორტული ვარჯიში, მარტივი შეძენა და სწრაფი მიწოდება.' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'galanz' SET vd.page_title = 'GALANZ | Superi.ge | აღმოაჩინე საუკეთესო შეთავაზებები', vd.meta_description = 'GALANZ არის წამყვანი ტექნიკის მწარმოებელი ბრენდი, რომელიც ცნობილია თავისი მაღალ ტექნოლოგიური და ხარისხიანი პროდუქციით. ჩვენ უზრუნველვყოფთ მომხმარებლისთვის თანამედროვე, ეფექტურ და სტილურ მოწყობილობებს, რომლებიც მიმართულია ყოველდღიური კომფორტისა და სამუშაო ' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'elenberg' SET vd.page_title = 'ELENBERG | Superi.ge', vd.meta_description = 'შეიძინეთ ELENBERG ის პროდუქცია საუკეთესო ფასად. მიიღეთ 2 წლიანი გარანტია და უფასო მიწოდება საქართველოს მასშტაბით' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'viewsonic' SET vd.page_title = 'ViewSonic | Superi.ge', vd.meta_description = 'იხილეთ ViewSonic-ის ბრენდის ინოვაციური მონიტორები,პროექტროები და სხვადასხვა პროდუქცა, რომლებიც იძლევა უპრეცედენტო სურათის ხარისხს და გამოსახულების სიზუსტეს. მაღალხარისხიანი ტექნოლოგიით, გეიმინგ პროდუქტების ფართო არჩევანით, ViewSonic ქმნის იდეალურ გადაწყვე' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'sokany' SET vd.page_title = 'SOKANY | Superi.ge', vd.meta_description = 'შეიძინე SOKANY ის ბრენდის გამორჩეული პროდუქცია SUPER ფასად.' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'nikai' SET vd.page_title = '', vd.meta_description = 'შეიძინეთ NIKAI ის ბრენდის საუკეთესო ტექნიკა გარანტიით.მიწოდება საქართველოს მასშტაბით' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'tamkera' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'evii' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'dysis' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'scheppach' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'ecoflow' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'tolsen' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'leo' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'kettler' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'nutribullet' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'ugreen' SET vd.page_title = '', vd.meta_description = 'UGREEN გთავაზობთ მაღალი ხარისხის ტექნიკურ აქსესუარებს, როგორიცაა კაბელები, დამტენები და ადაპტერები, რაც უზრუნველყოფს თქვენი მოწყობილობების სრულფასოვან მუშაობას' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'canyon' SET vd.page_title = 'CANYON', vd.meta_description = 'CANYON გთავაზობთ ინოვაციურ და ხარისხიან ტექნოლოგიურ აქსესუარებს, როგორიცაა კომპიუტერული periferიული მოწყობილობები, სმარტფონის აქსესუარები და ავტომობილური ტექნიკა. ბრენდი გამორჩეულია თავისი თანამედროვე დიზაინით, საიმედოობითა და მომხმარებელზე ორიენტირებული ' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'thomson' SET vd.page_title = 'Thomson', vd.meta_description = 'THOMSON - ის ბრენდი 1893 წელს საფრანგეთში დაარსდა, მას შემდეგ 130 წლიანი გამოცდილება დააგროვა და დღეს-დღეისობით ეს ბრენდი მოწინავე პოზიციას იკავებს ბაზარზე. ბრენდის მთავარი მიზანია: უახლესი ტექნოლოგიების შემუშავება და ის რომ მათი პროდუქცია ყველასათვის იყო' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'wokin' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'onvo' SET vd.page_title = '', vd.meta_description = 'ONVO - თანამედროვე ტექნიკის მწარმოებელი ბრენდი, რომელიც გთავაზობთ ხარისხიან და ინოვაციურ ელექტრონიკას. აღმოაჩინეთ ONVO-ს ტელევიზორები, სმარტ მოწყობილობები და სხვა საყოფაცხოვრებო ტექნიკა.' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'chiq' SET vd.page_title = '', vd.meta_description = 'ChiQ — ინოვაციური ტექნოლოგიების ბრენდი, რომელიც გთავაზობთ WiFi-ით მართვად ჭკვიან კონდიციონერებს იონიზაციის, თვითწმენდისა და ენერგოეფექტური ფუნქციებით. აღმოაჩინე ხარისხი და სმარტ კომფორტი CHiQ-თან ერთად.' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'lux-garden' SET vd.page_title = '', vd.meta_description = 'LUX GARDEN გთავაზობთ ხარისხიან და გამძლე ბაღის ტექნიკას – ბენზო სათიბელებს, ტრიმერებსა და სხვა მექანიზმებს, რომელიც შესაფერისია როგორც პროფესიონალური, ასევე საყოფაცხოვრებო გამოყენებისთვის' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'ariston' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'vivitek' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'msi-gaming' SET vd.page_title = 'MSI Gaming ლეპტოპები და კომპიუტერები', vd.meta_description = 'MSI – ლიდერი ინოვაციური ტექნოლოგიების სამყაროში MSI (Micro-Star International) არის გლობალურად აღიარებული ბრენდი, რომელიც სპეციალიზდება მაღალტექნოლოგიური და წარმადობის მხრივ მოწინავე პროდუქციის შექმნაში.' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'karma' SET vd.page_title = '', vd.meta_description = 'Karma-ის გაზის გამათბობლები უზრუნველყოფს ეფექტურ და უსაფრთხო გათბობას. მაღალი ხარისხის მასალებით დამზადებული მოდელები გამოირჩევიან ენერგოეფექტურობით, მარტივი მართვით და ხანგრძლივი საიმედოობით' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'thermaltake' SET vd.page_title = '', vd.meta_description = 'Thermaltake წარმოადგენს მაღალი ხარისხის გეიმერული და ПК კომპონენტების მწარმოებელს: კორპუსები, კვების ბლოკები, ქულერები, RGB განათება და აქსესუარები, შექმნილი შესრულებაზე, გამძლეობასა და ესთეტიკაზე ზრუნვით' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'urevo' SET vd.page_title = 'UREVO სარბენი ბილიკები – მაღალი ხარისხი, ჩუმი მუშაობა და დასაკეცი დიზაინი', vd.meta_description = 'UREVO გთავაზობთ სანდო და ჩუმად მომუშავე სარბენ ბილიკებს, ძლიერი ძრავით, ჩასაკეცი დიზაინით, მრავალ რეჟიმითა და მაღალი დატვირთვის შესაძლებლობით. იდეალურია სახლში ვარჯიშისთვის, უზრუნველყოფს კომფორტს, უსაფრთხოებას და გამძლეობას' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'kingsmith' SET vd.page_title = 'Kingsmith სარბენი ბილიკები – სმარტ ჩასაკეცი დიზაინი და მაღალი ხარისხი | Superi.ge', vd.meta_description = 'Kingsmith გთავაზობთ ინოვაციურ და ჩუმად მომუშავე სარბენ ბილიკებს, ჩასაკეცი დიზაინით, ჭკვიანი კონტროლით, მაღალი დატვირთვის შესაძლებლობითა და კომფორტული ვარჯიშისთვის შექმნილი სტრუქტურით. შეუხამეთ ხარისხი, სიმშვიდე და თანამედროვე ფიტნესი სახლში' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'thermex' SET vd.page_title = 'Thermex – წყლის გამაცხელებლები, ელექტრო ბოილერები და გამათბობლები | Superi.ge', vd.meta_description = 'THERMEX – სანდო და ენერგოეფექტური წყლის გამაცხელებლები, ბრტყელი და კლასიკური ბოილერები, სწრაფი გახურება, ხანგრძლივი რესურსი და მაღალი ხარისხი. შეიძინე Thermex-ის ოფიციალური პროდუქცია საუკეთესო ფასად Superi.ge-ზე' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'hmd' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'energizer' SET vd.page_title = 'Energizer – აკუმულატორები', vd.meta_description = 'Energizer აკუმულატორები და მაღალი ხარისხის ელემენტები Superi.ge-ზე. მეტი ენერგია, ხანგრძლივი მუშაობა და საიმედოობა ყველა მოწყობილობისთვის. ઝડપી მიწოდება საქართველოს მასშტაბით' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'eurosystems' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'samsung' SET vd.page_title = 'SAMSUNG | Superi.ge | აღმოაჩინე საუკეთესო შეთავაზებები', vd.meta_description = 'Samsung - ინოვაციის და ტექნოლოგიური ლიდერობა Samsung არის გლობალური ბრენდი, რომელიც ცნობილია თავისი უმაღლესი ხარისხის და ინოვაციური ტექნოლოგიური პროდუქტებით. ჩვენ გთავაზობთ ფართო სპექტრს თანამედროვე ტექნიკისა და ელექტრონიკის, რომელიც შექმნილია იმისათვი' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'xiaomi' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'apple' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'bosch' SET vd.page_title = 'Bosch | ბოში', vd.meta_description = 'დაათვალიერე SUPERI.GE-ზე ბოშის კატეგორია, შეარჩიე სამზარეულოს ან სხვა ტექნიკა სახლიდან გაუსვლელად და მიიღე შენაძენი უფასოდ და უსწრაფესად საქართველოს მასშტაბით.' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'alneo' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'allx' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = '2k' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'dreame' SET vd.page_title = '', vd.meta_description = 'DREAME გთავაზობთ ფართო სპექტრის ჭკვიან საყოფაცხოვრებო მოწყობილობებს: რობოტი და უსადენო მტვერსასრუტები, ჭკვიანი ფენები, ჰაერის ფილტრები, იონიზატორები და სხვა ინოვაციური ტექნიკა. მარტივი, ეფექტური და მაღალი ხარისხი თქვენი სახლისა და პირადი მოვლისთვის' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'inno3d' SET vd.page_title = 'INNO3D ვიდეო ბარათები – NVIDIA GeForce RTX გრაფიკული ბარათები | Superi', vd.meta_description = 'INNO3D ვიდეო ბარათები NVIDIA GeForce RTX სერიით. ძლიერი გრაფიკული ბარათები გეიმინგისთვის, ვიდეო მონტაჟისთვის და პროფესიონალური გამოყენებისთვის. შეარჩიეთ INNO3D გრაფიკული ბარათი საუკეთესო ფასად.' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'marazzi' SET vd.page_title = 'MARAZZI ტექნიკა საქართველოში | იტალიური ხარისხი და თანამედროვე საყოფაცხოვრებო ტექნიკა', vd.meta_description = 'აღმოაჩინეთ MARAZZI-ს თანამედროვე საყოფაცხოვრებო და კომერციული ტექნიკა Superi.ge-ზე. მაცივრები, სარეცხი მანქანები, კონდიციონერები, გამაგრილებლები და სხვა ტექნიკა ხარისხით, სტილითა და სანდოობით.' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'burio' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'shinever' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'wadfow' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'la-sommeliere' SET vd.page_title = 'La Sommelière', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'playseat' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'bernette' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'kukirin' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'roborock' SET vd.page_title = '', vd.meta_description = 'აღმოაჩინეთ Roborock-ის ჭკვიანი რობოტი მტვერსასრუტები. დაზოგეთ დრო და ენერგია უახლესი ტექნოლოგიებით. შეიძინეთ საუკეთესო ფასად და გარანტიით' WHERE vd.lang_code = 'ka';
-- UPDATE cscart_product_feature_variant_descriptions vd JOIN cscart_seo_names s ON s.object_id = vd.variant_id AND s.type = @et AND s.name = 'daikin' SET vd.page_title = '', vd.meta_description = '' WHERE vd.lang_code = 'ka';
