-- ============================================================================
-- superi.ge — 27: სარეცხი მანქანების კამპანია (ატვირთეთ სტატიის გამოქვეყნების შემდეგ!)
-- 1) „სარეცხი მანქანები“ კატეგორიას ემატება ბმული გზამკვლევზე (თუ უკვე არ არის).
-- 2) „საშრობი მანქანები“ და „ჩასაშენებელი სარეცხი მანქანები“ — სლოგანის ნაცვლად სრული ტექსტი (მხოლოდ თუ ტექსტი 300 სიმბოლოზე მოკლეა).
-- ძველი ტექსტები ინახება superi_bk_cat_27-ში. ხელახლა გაშვება უსაფრთხოა.
-- ============================================================================
SET NAMES utf8mb4;
CREATE TABLE IF NOT EXISTS superi_bk_cat_27 AS SELECT cd.category_id, cd.lang_code, s.name AS slug, cd.description FROM cscart_category_descriptions cd JOIN cscart_seo_names s ON s.object_id = cd.category_id AND s.type = 'c' AND s.lang_code = cd.lang_code AND s.company_id = 1 WHERE cd.lang_code = 'ka' AND s.name IN ('saretskhi-manqanebi', 'sashrobebi', 'chasashenebeli-saretskhi-manqanebi');
UPDATE cscart_category_descriptions cd JOIN cscart_seo_names s ON s.object_id = cd.category_id AND s.type = 'c' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'saretskhi-manqanebi' SET cd.description = CONCAT(IFNULL(cd.description, ''), '\n', '<p>დეტალური რჩევებისთვის წაიკითხეთ ჩვენი გზამკვლევი: <a href="https://superi.ge/rogor-shevarchiot-saretskhi-manqana/">როგორ შევარჩიოთ სარეცხი მანქანა</a>.</p>') WHERE cd.lang_code = 'ka' AND IFNULL(cd.description, '') NOT LIKE '%rogor-shevarchiot-saretskhi-manqana%';
UPDATE cscart_category_descriptions cd JOIN cscart_seo_names s ON s.object_id = cd.category_id AND s.type = 'c' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'sashrobebi' SET cd.description = '<p>საშრობი მანქანა სარეცხს ამინდისა და სეზონის მიუხედავად რამდენიმე საათში აშრობს — აივანზე ან ოთახში სარეცხის გაფენა აღარ გიწევთ, ტანსაცმელი კი რბილი და ნაკლებად დაჭმუჭნილი გამოდის. Superi.ge-ზე იპოვით 30-ზე მეტ საშრობ მანქანას ბრენდებისგან: <a href="https://superi.ge/bosch/">Bosch</a>, <a href="https://superi.ge/gorenje/">Gorenje</a>, <a href="https://superi.ge/beko/">Beko</a>, <a href="https://superi.ge/lg/">LG</a>, <a href="https://superi.ge/samsung/">Samsung</a>, <a href="https://superi.ge/midea/">Midea</a>, <a href="https://superi.ge/haier/">Haier</a>, <a href="https://superi.ge/toshiba/">Toshiba</a> და <a href="https://superi.ge/aeg/">AEG</a>.</p>
<h2>როგორ შევარჩიოთ საშრობი მანქანა</h2>
<ul>
<li><strong>ტიპი:</strong> თბური ტუმბოს (Heat Pump) საშრობი ყველაზე ეკონომიურია და ქსოვილს დაბალ ტემპერატურაზე, ფრთხილად აშრობს; კონდენსაციური საშრობი უფრო ხელმისაწვდომია და სწრაფად აშრობს. ორივე სავენტილაციო მილის გარეშე მუშაობს.</li>
<li><strong>ტევადობა:</strong> საშრობის ტევადობა სარეცხი მანქანისას უნდა უდრიდეს ან აღემატებოდეს — 8 კგ-იანი სარეცხი მანქანისთვის აირჩიეთ 8–9 კგ-იანი საშრობი.</li>
<li><strong>სენსორული გაშრობა:</strong> სენსორი ტენიანობას ზომავს და საშრობს თავად აჩერებს, როცა სარეცხი გაშრება — ასე დენს ზოგავთ და ქსოვილს არ აზიანებთ.</li>
<li><strong>პროგრამები:</strong> შალის, პერანგების, ბავშვის ტანსაცმლისა და ნაოჭების საწინააღმდეგო პროგრამები ზრუნვას ამარტივებს.</li>
<li><strong>დამონტაჟება:</strong> საშრობი შეგიძლიათ სარეცხ მანქანაზე დადგათ სპეციალური დამაკავშირებელი ნაკრებით — ასე ადგილს დაზოგავთ.</li>
</ul>
<p>დეტალური რჩევებისთვის წაიკითხეთ ჩვენი გზამკვლევი: <a href="https://superi.ge/rogor-shevarchiot-saretskhi-manqana/">როგორ შევარჩიოთ სარეცხი მანქანა</a>. შეძენა Superi.ge-ზე შეგიძლიათ ნაწილ-ნაწილ გადახდით; თბილისში მიწოდება უფასოა 100₾-დან, ასევე ვაწვდით მთელ საქართველოში. იხილეთ ასევე <a href="https://superi.ge/saretskhi-manqanebi/">სარეცხი მანქანები</a> და <a href="https://superi.ge/chasashenebeli-saretskhi-manqanebi/">ჩასაშენებელი სარეცხი მანქანები</a>.</p>' WHERE cd.lang_code = 'ka' AND CHAR_LENGTH(REGEXP_REPLACE(IFNULL(cd.description, ''), '<[^>]*>', '')) < 300;
UPDATE cscart_category_descriptions cd JOIN cscart_seo_names s ON s.object_id = cd.category_id AND s.type = 'c' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'chasashenebeli-saretskhi-manqanebi' SET cd.description = '<p>ჩასაშენებელი სარეცხი მანქანა სამზარეულოს ან აბაზანის კარადაში მონტაჟდება და ავეჯის ფასადს ეფარება — ინტერიერში საერთოდ არ ჩანს და სივრცეს ზოგავს. Superi.ge-ზე იპოვით ჩასაშენებელ სარეცხ მანქანებს <a href="https://superi.ge/electrolux/">Electrolux</a> და <a href="https://superi.ge/beko/">Beko</a>-სგან, ასევე ჩასაშენებელ სარეცხ მანქანებს საშრობით <a href="https://superi.ge/beko/">Beko</a> და <a href="https://superi.ge/bosch/">Bosch</a>-სგან.</p>
<h2>როგორ შევარჩიოთ ჩასაშენებელი სარეცხი მანქანა</h2>
<ul>
<li><strong>ზომა:</strong> ჩასაშენებელი მოდელები, როგორც წესი, დაახლოებით 82 სმ სიმაღლისაა, რომ სამზარეულოს სამუშაო ზედაპირის ქვეშ ჩაეტიოს. ყიდვამდე გაზომეთ ნიშის სიგანე, სიღრმე და სიმაღლე.</li>
<li><strong>ფასადი:</strong> მანქანის კარზე ავეჯის ფასადი მაგრდება, ამიტომ კარადის კარი და სარეცხი მანქანა ერთად იღება.</li>
<li><strong>ტევადობა:</strong> ჩასაშენებელი მოდელები, ჩვეულებრივ, 7–8 კგ-იანია — 2–4 კაციანი ოჯახისთვის საკმარისი.</li>
<li><strong>საშრობით:</strong> ჩასაშენებელი სარეცხი მანქანა საშრობით რეცხავს და აშრობს — ცალკე საშრობისთვის ადგილი აღარ გჭირდებათ.</li>
<li><strong>ხმაური:</strong> კარადაში ჩაშენებული მანქანა ისედაც ჩუმია, მაგრამ ღია სამზარეულოსთვის მაინც აირჩიეთ ინვერტორული ძრავის მქონე მოდელი.</li>
</ul>
<p>დეტალური რჩევებისთვის წაიკითხეთ ჩვენი გზამკვლევი: <a href="https://superi.ge/rogor-shevarchiot-saretskhi-manqana/">როგორ შევარჩიოთ სარეცხი მანქანა</a>. შეძენა Superi.ge-ზე შეგიძლიათ ნაწილ-ნაწილ გადახდით; თბილისში მიწოდება უფასოა 100₾-დან, ასევე ვაწვდით მთელ საქართველოში. იხილეთ ასევე <a href="https://superi.ge/saretskhi-manqanebi/">სარეცხი მანქანები</a>, <a href="https://superi.ge/sashrobebi/">საშრობი მანქანები</a> და <a href="https://superi.ge/churchelis-sarecxhi-manqanebi/">ჭურჭლის სარეცხი მანქანები</a>.</p>' WHERE cd.lang_code = 'ka' AND CHAR_LENGTH(REGEXP_REPLACE(IFNULL(cd.description, ''), '<[^>]*>', '')) < 300;
SELECT s.name AS slug, CHAR_LENGTH(REGEXP_REPLACE(IFNULL(cd.description, ''), '<[^>]*>', '')) AS text_chars, cd.description LIKE '%rogor-shevarchiot-saretskhi-manqana%' AS has_guide_link FROM cscart_category_descriptions cd JOIN cscart_seo_names s ON s.object_id = cd.category_id AND s.type = 'c' AND s.lang_code = 'ka' AND s.company_id = 1 WHERE cd.lang_code = 'ka' AND s.name IN ('saretskhi-manqanebi', 'sashrobebi', 'chasashenebeli-saretskhi-manqanebi');
-- დაბრუნება: UPDATE cscart_category_descriptions cd JOIN superi_bk_cat_27 b ON b.category_id = cd.category_id AND b.lang_code = cd.lang_code SET cd.description = b.description;
