-- ============================================================================
-- superi.ge — 28: ნაძვის ხეების კამპანია (ატვირთეთ სტატიის გამოქვეყნების შემდეგ!)
-- 1) „ნაძვის ხეები“ და „საახალწლო“ — ზოგადი ტექსტის ნაცვლად სრული ტექსტი, ბმულებით სტატიაზე და პოპულარულ მოდელებზე.
--    + მეტა აღწერა (მხოლოდ თუ ცარიელია).
-- 2) „ნაძვის ხე - 270 სმ (2355-210)“ → „ნაძვის ხე 210 სმ (2355-210)“ (სინამდვილეში 210 სმ-ია) + აღწერაში „დათოვლილი“ → „სადა მწვანე“.
-- 3) 23SN2732 სერიის 210/270/300 სმ — სახელს ემატება „დათოვლილი“ (როგორც 180 სმ-იანს).
-- 4) აღწერებში შეცდომა „აწყობის მტიპი“ → „აწყობის ტიპი“.
-- ასლები: superi_bk_cat_28, superi_bk_prod_28. ხელახლა გაშვება უსაფრთხოა. დაბრუნება ბოლოშია.
-- ============================================================================
SET NAMES utf8mb4;
CREATE TABLE IF NOT EXISTS superi_bk_cat_28 AS SELECT cd.category_id, cd.lang_code, s.name AS slug, cd.description, cd.meta_description FROM cscart_category_descriptions cd JOIN cscart_seo_names s ON s.object_id = cd.category_id AND s.type = 'c' AND s.lang_code = 'ka' AND s.company_id = 1 WHERE cd.lang_code = 'ka' AND s.name IN ('nadzvisxe', 'saakhaltslo');
CREATE TABLE IF NOT EXISTS superi_bk_prod_28 AS SELECT pd.product_id, pd.lang_code, pd.product, pd.page_title, pd.meta_description, pd.full_description FROM cscart_product_descriptions pd LEFT JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 WHERE pd.lang_code = 'ka' AND (s.name IN ('nadzvis-khe-210-sm-23sn2732-210', 'nadzvis-khe-270-sm-23sn2732-270', 'nadzvis-khe-300-sm-23sn2732-300', 'nadzvis-khe-270-sm-2355-210') OR pd.full_description LIKE '%აწყობის მტიპი%');
UPDATE cscart_category_descriptions cd JOIN cscart_seo_names s ON s.object_id = cd.category_id AND s.type = 'c' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'nadzvisxe' SET cd.description = '<p>ნაძვის ხე საახალწლო სახლის მთავარი დეკორაციაა. Superi.ge-ზე იპოვით ხელოვნურ ნაძვის ხეებს 150-დან 300 სმ-მდე: კლასიკურ მწვანეს, დათოვლილს, გირჩებითა და კენკრით გაფორმებულსა და თეთრს. ხელოვნური ნაძვის ხე წიწვს არ ყრის, მორწყვა არ სჭირდება და სწორი მოვლით წლების განმავლობაში გემსახურებათ.</p>
<h2>როგორ შევარჩიოთ ხელოვნური ნაძვის ხე</h2>
<ul>
<li><strong>სიმაღლე:</strong> ჭერის სიმაღლეს გამოაკელით 30–40 სმ: 2.5–2.6 მ ჭერისთვის შეარჩიეთ 180–210 სმ, 2.8 მ-ისთვის — 240 სმ, 3 მ-ისთვის — 270 სმ. მაღალი ჭერის, დარბაზისა და ოფისისთვის გვაქვს 300 სმ-იანი ნაძვის ხეებიც.</li>
<li><strong>სიგანე:</strong> ერთი და იგივე სიმაღლის ნაძვის ხეები სიგანით განსხვავდება — მაგალითად, 210 სმ-იანი მოდელების დიამეტრი 105-დან 140 სმ-მდეა. პატარა ოთახისთვის აირჩიეთ ვიწრო, დიდი მისაღებისთვის კი ფუმფულა მოდელი.</li>
<li><strong>წიწვი:</strong> PVC წიწვი ნაძვის ხეს სიხშირეს აძლევს, სილიკონის (ჩამოსხმული) წიწვი კი ცოცხალ ნაძვს ჰგავს. საუკეთესო ბალანსს კომბინირებული მოდელები იძლევა.</li>
<li><strong>სტილი:</strong> მწვანე ნაძვის ხე კლასიკაა და ნებისმიერ სათამაშოს უხდება; დათოვლილი სათამაშოების გარეშეც ზამთრის განწყობას ქმნის; გირჩებითა და კენკრით გაფორმებული კი უკვე მზადაა დღესასწაულისთვის.</li>
<li><strong>აწყობა:</strong> გადმოსაშლელი (ავტომატური) ნაძვის ხე რამდენიმე წუთში იწყობა, რადგან ტოტები ღეროზე უკვე მიმაგრებულია. ჩასამაგრებელი ტოტების მქონე მოდელი კი დაშლილი უფრო კომპაქტურად ინახება.</li>
</ul>
<p>ყველაზე მოთხოვნადი ზომაა 210 სმ — მაგალითად, <a href="https://superi.ge/nadzvis-khe-himalai-210-sm-bc-210/">ნაძვის ხე ჰიმალაი 210 სმ</a>, <a href="https://superi.ge/nadzvis-khe-dublini-210-sm-aa-210/">ნაძვის ხე დუბლინი 210 სმ</a> და <a href="https://superi.ge/datovlili-nadzvis-khe-210-sm-2223-210/">დათოვლილი ნაძვის ხე 210 სმ</a>. დეკემბერში მოთხოვნა მკვეთრად იზრდება, ამიტომ სასურველი ზომა წინასწარ შეარჩიეთ.</p>
<p>დეტალური რჩევებისთვის წაიკითხეთ ჩვენი გზამკვლევი: <a href="https://superi.ge/rogor-shevarchiot-nadzvis-khe/">როგორ შევარჩიოთ ხელოვნური ნაძვის ხე</a>. შეძენა Superi.ge-ზე შეგიძლიათ ნაწილ-ნაწილ გადახდით; თბილისში მიწოდება უფასოა 100₾-დან, ასევე ვაწვდით მთელ საქართველოში.</p>' WHERE cd.lang_code = 'ka' AND IFNULL(cd.description, '') NOT LIKE '%rogor-shevarchiot-nadzvis-khe%' AND CHAR_LENGTH(REGEXP_REPLACE(IFNULL(cd.description, ''), '<[^>]*>', '')) < 800;
UPDATE cscart_category_descriptions cd JOIN cscart_seo_names s ON s.object_id = cd.category_id AND s.type = 'c' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'nadzvisxe' SET cd.meta_description = 'ხელოვნური ნაძვის ხეები 150-დან 300 სმ-მდე: მწვანე, დათოვლილი და გირჩებით გაფორმებული, ადვილად ასაწყობი მოდელები. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება მთელ საქართველოში.' WHERE cd.lang_code = 'ka' AND IFNULL(cd.meta_description, '') = '';
UPDATE cscart_category_descriptions cd JOIN cscart_seo_names s ON s.object_id = cd.category_id AND s.type = 'c' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'saakhaltslo' SET cd.description = '<p>მოემზადეთ ახალი წლისთვის Superi.ge-სთან ერთად! აქ თავმოყრილია ხელოვნური ნაძვის ხეები 150-დან 300 სმ-მდე — მწვანე, დათოვლილი, გირჩებითა და კენკრით გაფორმებული და თეთრი მოდელები სახლის, ოფისისა და დარბაზისთვის.</p>
<p>ყველა მოდელი იხილეთ კატეგორიაში <a href="https://superi.ge/nadzvisxe/">ნაძვის ხეები</a>, ხოლო სწორი ზომისა და ტიპის შესარჩევად წაიკითხეთ ჩვენი გზამკვლევი: <a href="https://superi.ge/rogor-shevarchiot-nadzvis-khe/">როგორ შევარჩიოთ ხელოვნური ნაძვის ხე</a>. საახალწლო საჩუქრად კი შეარჩიეთ <a href="https://superi.ge/mobiluri-teleponebi/">მობილური ტელეფონები</a>, <a href="https://superi.ge/televizorebi/">ტელევიზორები</a>, <a href="https://superi.ge/aerogrilebi/">აეროგრილები</a> და <a href="https://superi.ge/hoverbordebi/">ჰოვერბორდები</a>.</p>
<p>შეძენა Superi.ge-ზე შეგიძლიათ ნაწილ-ნაწილ გადახდით; თბილისში მიწოდება უფასოა 100₾-დან, ასევე ვაწვდით მთელ საქართველოში.</p>' WHERE cd.lang_code = 'ka' AND IFNULL(cd.description, '') NOT LIKE '%rogor-shevarchiot-nadzvis-khe%' AND CHAR_LENGTH(REGEXP_REPLACE(IFNULL(cd.description, ''), '<[^>]*>', '')) < 800;
UPDATE cscart_category_descriptions cd JOIN cscart_seo_names s ON s.object_id = cd.category_id AND s.type = 'c' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'saakhaltslo' SET cd.meta_description = 'საახალწლო ნაძვის ხეები Superi.ge-ზე: ხელოვნური მწვანე და დათოვლილი მოდელები 150–300 სმ. ✓ ნაწილ-ნაწილ გადახდა ✓ უფასო მიწოდება თბილისში 100₾-დან.' WHERE cd.lang_code = 'ka' AND IFNULL(cd.meta_description, '') = '';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'nadzvis-khe-270-sm-2355-210' SET pd.product = REPLACE(pd.product, '- 270 სმ (2355-210)', '210 სმ (2355-210)'), pd.page_title = REPLACE(pd.page_title, '- 270 სმ (2355-210)', '210 სმ (2355-210)'), pd.meta_description = REPLACE(pd.meta_description, '- 270 სმ (2355-210)', '210 სმ (2355-210)'), pd.full_description = REPLACE(pd.full_description, 'გაფორმება: დათოვლილი |', 'გაფორმება: სადა მწვანე |') WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name IN ('nadzvis-khe-210-sm-23sn2732-210', 'nadzvis-khe-270-sm-23sn2732-270', 'nadzvis-khe-300-sm-23sn2732-300') SET pd.product = CONCAT('დათოვლილი ', pd.product), pd.page_title = IF(pd.page_title LIKE 'ნაძვის ხე %', CONCAT('დათოვლილი ', pd.page_title), pd.page_title) WHERE pd.lang_code = 'ka' AND pd.product LIKE 'ნაძვის ხე %';
UPDATE cscart_product_descriptions pd SET pd.full_description = REPLACE(pd.full_description, 'აწყობის მტიპი', 'აწყობის ტიპი') WHERE pd.lang_code = 'ka' AND pd.full_description LIKE '%აწყობის მტიპი%';
SELECT s.name AS slug, CHAR_LENGTH(REGEXP_REPLACE(IFNULL(cd.description, ''), '<[^>]*>', '')) AS text_chars, cd.description LIKE '%rogor-shevarchiot-nadzvis-khe%' AS has_guide_link, cd.meta_description FROM cscart_category_descriptions cd JOIN cscart_seo_names s ON s.object_id = cd.category_id AND s.type = 'c' AND s.lang_code = 'ka' AND s.company_id = 1 WHERE cd.lang_code = 'ka' AND s.name IN ('nadzvisxe', 'saakhaltslo');
SELECT s.name AS slug, pd.product, pd.page_title FROM cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 WHERE pd.lang_code = 'ka' AND s.name IN ('nadzvis-khe-210-sm-23sn2732-210', 'nadzvis-khe-270-sm-23sn2732-270', 'nadzvis-khe-300-sm-23sn2732-300', 'nadzvis-khe-270-sm-2355-210');
SELECT COUNT(*) AS left_typos FROM cscart_product_descriptions WHERE lang_code = 'ka' AND full_description LIKE '%აწყობის მტიპი%';
-- დაბრუნება (საჭიროების შემთხვევაში):
-- UPDATE cscart_category_descriptions cd JOIN superi_bk_cat_28 b ON b.category_id = cd.category_id AND b.lang_code = cd.lang_code SET cd.description = b.description, cd.meta_description = b.meta_description;
-- UPDATE cscart_product_descriptions pd JOIN superi_bk_prod_28 b ON b.product_id = pd.product_id AND b.lang_code = pd.lang_code SET pd.product = b.product, pd.page_title = b.page_title, pd.meta_description = b.meta_description, pd.full_description = b.full_description;
