-- ============================================================================
-- superi.ge — 29: გენერატორების კამპანია (ატვირთეთ სტატიის გამოქვეყნების შემდეგ!)
-- 1) „გენერატორები“ — სრული ტექსტი (3 კვტ, 5 კვტ, ინვერტორული, მინი, ელექტროსადგური) ბმულებით სტატიაზე, ბრენდებსა და პოპულარულ მოდელებზე
--    + მეტა აღწერა (მხოლოდ თუ ცარიელია).
-- 2) SHINEVER YG5000IS / YG7500PRO-C: „ინვერტერული“ → „ინვერტორული“ სახელსა და სათაურში.
-- 3) აღწერებში შეცდომები: „ელექტორნული“, „სტატრერით“, „thanks to“, „ოთხ ცილინდრიანი“, „p&gt;“, DELTA mini-ს ბეჭდვითი შეცდომები.
-- 4) SHINEVER LD1032 (100 კვტ): აღწერაში ეწერა „მოდელი: LD1030“ და „სიმძლავრე: 50 kW“ → შესწორდა LD1032 / 100 kW.
-- ასლები: superi_bk_cat_29, superi_bk_prod_29. ხელახლა გაშვება უსაფრთხოა. დაბრუნება ბოლოშია.
-- ============================================================================
SET NAMES utf8mb4;
CREATE TABLE IF NOT EXISTS superi_bk_cat_29 AS SELECT cd.category_id, cd.lang_code, s.name AS slug, cd.description, cd.meta_description FROM cscart_category_descriptions cd JOIN cscart_seo_names s ON s.object_id = cd.category_id AND s.type = 'c' AND s.lang_code = 'ka' AND s.company_id = 1 WHERE cd.lang_code = 'ka' AND s.name IN ('generatorebi');
CREATE TABLE IF NOT EXISTS superi_bk_prod_29 AS SELECT DISTINCT pd.product_id, pd.lang_code, pd.product, pd.page_title, pd.meta_description, pd.full_description FROM cscart_product_descriptions pd LEFT JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 WHERE pd.lang_code = 'ka' AND (s.name IN ('ecoflow-delta-mini', 'shinever-ld1032-100kw', 'shinever-yg5000is-4-4kw', 'shinever-yg7500pro-c-6-5kw', 'tolsen-tol1763-79992-5-5kw') OR pd.full_description LIKE '%ელექტორნული%' OR pd.full_description LIKE '%სტატრერით%' OR pd.full_description LIKE '%thanks to სახელური + ბორბლები%' OR pd.full_description LIKE '%ბენზინი, ოთხ ცილინდრიანი%');
UPDATE cscart_category_descriptions cd JOIN cscart_seo_names s ON s.object_id = cd.category_id AND s.type = 'c' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'generatorebi' SET cd.description = '<p>გენერატორი დენის გათიშვისას სახლს, აგარაკს, მაღაზიას თუ სამშენებლო ობიექტს დამოუკიდებელ ელექტროენერგიას აძლევს. Superi.ge-ზე იპოვით გენერატორებს 0.5-დან 100 კვტ-მდე — ბენზინის, დიზელის და ინვერტორულ მოდელებს, ასევე პორტატულ ელექტროსადგურებს ბრენდებისგან: <a href="https://superi.ge/konner-and-sohnen/">Konner&Sohnen</a>, <a href="https://superi.ge/schpindel/">Schpindel</a>, <a href="https://superi.ge/ingco/">INGCO</a>, <a href="https://superi.ge/tolsen/">TOLSEN</a>, <a href="https://superi.ge/scheppach/">Scheppach</a>, <a href="https://superi.ge/al-ko/">AL-KO</a>, <a href="https://superi.ge/shinever/">SHINEVER</a> და <a href="https://superi.ge/ecoflow/">EcoFlow</a>.</p>
<h2>როგორ შევარჩიოთ გენერატორი</h2>
<ul>
<li><strong>სიმძლავრე:</strong> შეკრიბეთ ყველა ტექნიკის სიმძლავრე, რომელიც ერთად უნდა იმუშაოს, და დაუმატეთ 20–30% მარაგი. ბინისა და აგარაკისთვის ხშირად საკმარისია 3 კვტ-იანი გენერატორი, კერძო სახლისთვის წყლის ტუმბოთი და სარეცხი მანქანით — 5–7 კვტ. არჩევისას ნომინალურ სიმძლავრეს უყურეთ და არა მაქსიმალურს.</li>
<li><strong>ინვერტორული თუ ჩვეულებრივი:</strong> ინვერტორული გენერატორი გლუვ, სტაბილურ ძაბვას იძლევა — უსაფრთხოა ტელევიზორის, კომპიუტერისა და გაზის ქვაბისთვის, ჩუმია და საწვავს ზოგავს. ჩვეულებრივი გენერატორი AVR-ით უფრო ხელმისაწვდომია და კარგია ხელსაწყოების, ტუმბოსა და გამათბობლისთვის.</li>
<li><strong>ბენზინი თუ დიზელი:</strong> ბენზინის გენერატორი მსუბუქი და ხელმისაწვდომია პერიოდული გათიშვებისთვის; დიზელის გენერატორი ეკონომიური და გამძლეა ხანგრძლივი, უწყვეტი მუშაობისთვის და ბიზნესისთვის.</li>
<li><strong>ელექტროსადგური:</strong> პორტატული ელექტროსადგური (EcoFlow) უხმაუროა და გამონაბოლქვი არ აქვს, ამიტომ ბინაშიც გამოიყენება — იდეალურია როუტერის, შუქის, ლეპტოპისა და გაზის ქვაბისთვის მოკლე გათიშვებისას.</li>
<li><strong>დაქოქვა და ATS:</strong> ელექტრო ან დისტანციური დაქოქვა მოსახერხებელია, ATS კი დენის გათიშვისას გენერატორს ავტომატურად რთავს. სამფაზიანი ტექნიკისთვის აირჩიეთ 230/400 V მოდელი.</li>
</ul>
<p><strong>პოპულარული მოდელები:</strong> 3 კვტ-იანი გენერატორები — <a href="https://superi.ge/konner-and-sohnen-ks-3000e-3kw/">Konner&Sohnen KS 3000E</a>, <a href="https://superi.ge/tolsen-tol1762-79991-3000w/">TOLSEN TOL1762</a> და <a href="https://superi.ge/schpindel-schi-169009-2-8kw-x208cc/">Schpindel 2.8 კვტ</a>; 5 კვტ და მეტი — <a href="https://superi.ge/konner-and-sohnen-ks-7000-5-5kw/">Konner&Sohnen KS 7000</a>, <a href="https://superi.ge/leo-kb5000e-5kw/">LEO KB5000E</a> და <a href="https://superi.ge/ingco-ge65006-6-5/">INGCO GE65006</a>; ინვერტორული — <a href="https://superi.ge/konner-and-sohnen-ksb-22i-s-2000w/">Konner&Sohnen KSB 22i S</a> და <a href="https://superi.ge/scheppach-sg-3400i-3400w/">Scheppach SG 3400i</a>; მინი გენერატორები — <a href="https://superi.ge/wadfow-wgeaa01-0-8-kw/">WADFOW 0.8 კვტ</a> და <a href="https://superi.ge/ingco-ge8002/">INGCO GE8002</a>.</p>
<p><strong>უსაფრთხოება:</strong> გენერატორი მხოლოდ გარეთ ჩართეთ — არასოდეს სახლში, ავტოფარეხში ან დახურულ აივანზე, რადგან გამონაბოლქვი მხუთავ აირს შეიცავს.</p>
<p>დეტალური რჩევებისთვის წაიკითხეთ ჩვენი გზამკვლევი: <a href="https://superi.ge/rogor-shevarchiot-generatori/">როგორ შევარჩიოთ გენერატორი</a>. შეძენა Superi.ge-ზე შეგიძლიათ ნაწილ-ნაწილ გადახდით; თბილისში მიწოდება უფასოა 100₾-დან, ასევე ვაწვდით მთელ საქართველოში.</p>' WHERE cd.lang_code = 'ka' AND IFNULL(cd.description, '') NOT LIKE '%rogor-shevarchiot-generatori%' AND CHAR_LENGTH(REGEXP_REPLACE(IFNULL(cd.description, ''), '<[^>]*>', '')) < 800;
UPDATE cscart_category_descriptions cd JOIN cscart_seo_names s ON s.object_id = cd.category_id AND s.type = 'c' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'generatorebi' SET cd.meta_description = 'გენერატორები 0.5-დან 100 კვტ-მდე: ბენზინის, დიზელის და ინვერტორული, 3 და 5 კვტ-იანი მოდელები და EcoFlow ელექტროსადგურები. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება მთელ საქართველოში.' WHERE cd.lang_code = 'ka' AND IFNULL(cd.meta_description, '') = '';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name IN ('shinever-yg5000is-4-4kw', 'shinever-yg7500pro-c-6-5kw') SET pd.product = REPLACE(pd.product, 'ინვერტერული', 'ინვერტორული'), pd.page_title = REPLACE(pd.page_title, 'ინვერტერული', 'ინვერტორული') WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd SET pd.full_description = REPLACE(pd.full_description, 'ელექტორნული', 'ელექტრონული') WHERE pd.lang_code = 'ka' AND pd.full_description LIKE '%ელექტორნული%';
UPDATE cscart_product_descriptions pd SET pd.full_description = REPLACE(pd.full_description, 'სტატრერით', 'სტარტერით') WHERE pd.lang_code = 'ka' AND pd.full_description LIKE '%სტატრერით%';
UPDATE cscart_product_descriptions pd SET pd.full_description = REPLACE(pd.full_description, 'thanks to სახელური + ბორბლები', 'სახელურისა და ბორბლების დახმარებით') WHERE pd.lang_code = 'ka' AND pd.full_description LIKE '%thanks to სახელური + ბორბლები%';
UPDATE cscart_product_descriptions pd SET pd.full_description = REPLACE(pd.full_description, 'ბენზინი, ოთხ ცილინდრიანი', 'ბენზინი, ოთხტაქტიანი') WHERE pd.lang_code = 'ka' AND pd.full_description LIKE '%ბენზინი, ოთხ ცილინდრიანი%';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'tolsen-tol1763-79992-5-5kw' SET pd.full_description = REPLACE(pd.full_description, '<p>p&gt;ბენზინის მძლავრი', '<p>ბენზინის მძლავრი') WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'ecoflow-delta-mini' SET pd.full_description = REPLACE(pd.full_description, 'როგოეც', 'როგორც') WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'ecoflow-delta-mini' SET pd.full_description = REPLACE(pd.full_description, 'მწყობილობის', 'მოწყობილობის') WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'ecoflow-delta-mini' SET pd.full_description = REPLACE(pd.full_description, 'დატენავს', 'დატენვას') WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'shinever-ld1032-100kw' SET pd.full_description = REPLACE(pd.full_description, 'მოდელი: LD1030', 'მოდელი: LD1032') WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'shinever-ld1032-100kw' SET pd.full_description = REPLACE(pd.full_description, 'სიმძლავრე: 50 kW', 'სიმძლავრე: 100 kW') WHERE pd.lang_code = 'ka';
SELECT s.name AS slug, CHAR_LENGTH(REGEXP_REPLACE(IFNULL(cd.description, ''), '<[^>]*>', '')) AS text_chars, cd.description LIKE '%rogor-shevarchiot-generatori%' AS has_guide_link, cd.meta_description FROM cscart_category_descriptions cd JOIN cscart_seo_names s ON s.object_id = cd.category_id AND s.type = 'c' AND s.lang_code = 'ka' AND s.company_id = 1 WHERE cd.lang_code = 'ka' AND s.name = 'generatorebi';
SELECT s.name AS slug, pd.product FROM cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 WHERE pd.lang_code = 'ka' AND s.name IN ('shinever-yg5000is-4-4kw', 'shinever-yg7500pro-c-6-5kw');
SELECT COUNT(*) AS typos_left FROM cscart_product_descriptions WHERE lang_code = 'ka' AND (full_description LIKE '%ელექტორნული%' OR full_description LIKE '%სტატრერით%' OR full_description LIKE '%thanks to სახელური + ბორბლები%' OR full_description LIKE '%ბენზინი, ოთხ ცილინდრიანი%' OR full_description LIKE '%p&gt;ბენზინის მძლავრი%' OR full_description LIKE '%მოდელი: LD1030%სიმძლავრე: 50 kW%' AND product LIKE '%LD1032%');
-- დაბრუნება (საჭიროების შემთხვევაში):
-- UPDATE cscart_category_descriptions cd JOIN superi_bk_cat_29 b ON b.category_id = cd.category_id AND b.lang_code = cd.lang_code SET cd.description = b.description, cd.meta_description = b.meta_description;
-- UPDATE cscart_product_descriptions pd JOIN superi_bk_prod_29 b ON b.product_id = pd.product_id AND b.lang_code = pd.lang_code SET pd.product = b.product, pd.page_title = b.page_title, pd.meta_description = b.meta_description, pd.full_description = b.full_description;
