-- ============================================================================
-- superi.ge — 37: სეიფების კატეგორია — უნიკალური მეტა აღწერა (SEO description) 48 პროდუქტზე
-- თითოეული იწერება პროდუქტის რეალური მახასიათებლებით (საკეტი, მოცულობა, ზომა, წონა, ცეცხლგამძლეობა), 160 სიმბოლომდე.
-- სათაურს (page title) არ ეხება. ძველი მნიშვნელობები ინახება superi_bk_meta_37-ში. დაბრუნება ბოლოშია.
-- ============================================================================
SET NAMES utf8mb4;
CREATE TABLE IF NOT EXISTS superi_bk_meta_37 AS SELECT pd.product_id, pd.lang_code, pd.meta_description FROM cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 WHERE pd.lang_code = 'ka' AND s.name IN ('aiko-chirok-1312', 'aiko-t-140-el', 'aiko-t-140-kl', 'aiko-t-17', 'aiko-t-17-el', 'aiko-t-230-el', 'aiko-t-280-el', 'aiko-t-280-kl', 'aiko-tm-120t-el', 'aiko-tm-25-el', 'aiko-tm-63t-el', 'aiko-filin-32', 'aiko-chirok-1015', 'aiko-key-20', 'aiko-key-60', '420ea-20x42x35', '17e-17x23x17', 'mdtb-vega-33-e', 'valberg-frs-73-t-kl-73-2x48-5x43', 'valberg-frs-36-kl-36x48x43', 'valberg-frs-36-el-36x48x43', 'valberg-frs-30-el-30x40-5x35-5', 'aiko-chirok-1020-100x30x20', 'valberg-frs-30-kl-30x40-5x35-5', 'mn1', 'fd20-31x29x20', 'aiko-chirok-1318', 'aiko-chirok-1320', 'aiko-sl-125t', 'aiko-chirok-1400x620x300', '170x230x170-17ef', 'aiko-sl-87t', '170x230x170-17ck', '250x350x250-25scl', '115x85x40-12k-3', 'gn-safe', '1541', 'f400-group-limited', '20sce-200x310x200', 'f0901s-200x310x200', 'filin-35-1390x424x219', '25x8-5x20', '15x8x12', '30x9x24-5', 'safewell-30sav-300x380x300-mm-11', '22x35x27-masterlock', '19-4x29x26-4-masterlock', '18x43x37-masterlock');

UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'aiko-chirok-1312' SET pd.meta_description = 'იარაღის სეიფი AIKO Chirok 1312 — 2 თოფისთვის, ცალკე განყოფილება ვაზნებისთვის, 2 გასაღების საკეტი, 130×20×12 სმ, 11 კგ. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'aiko-t-140-el' SET pd.meta_description = 'სეიფი Aiko T-140 EL — ელექტრონული კოდური საკეტი ავარიული გახსნით, 2.5 ლ, 14×19.5×14 სმ. ფულის, სამკაულისა და საბუთებისთვის. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'aiko-t-140-kl' SET pd.meta_description = 'სეიფი Aiko T-140 KL — გასაღებით, 2.5 ლ, 14×19.5×14 სმ, 3 კგ, კედელზე დასამაგრებელი. კომპაქტური სეიფი სახლისა და ოფისისთვის. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'aiko-t-17' SET pd.meta_description = 'სეიფი Aiko T-17 — გასაღებით, 7 ლ, 17×26×23 სმ, 4 კგ, იატაკზე ან კედელზე დასამაგრებელი. საბუთებისა და ძვირფასეულობისთვის. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'aiko-t-17-el' SET pd.meta_description = 'სეიფი Aiko T-17.EL — ელექტრონული კოდით და ავარიული გახსნით, 7 ლ, 17×26×23 სმ, 4 კგ. საბუთებისა და ძვირფასეულობისთვის. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'aiko-t-230-el' SET pd.meta_description = 'სეიფი Aiko T-230 EL — ელექტრონული კოდური საკეტი, 14 ლ, 23×31×25 სმ, 5 კგ, ფოლადის კორპუსი. სახლისა და ოფისისთვის. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'aiko-t-280-el' SET pd.meta_description = 'სეიფი Aiko T-280 EL — ელექტრონული კოდით, 25 ლ, 2 განყოფილება, 28×35×30 სმ, 8 კგ. საბუთებისა და ფასეულობისთვის. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'aiko-t-280-kl' SET pd.meta_description = 'სეიფი Aiko T-280 KL — გასაღებით, 25 ლ, 2 განყოფილება, 28×35×30 სმ, 8 კგ. საიმედო სეიფი სახლისა და ოფისისთვის. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება მთელ საქართველოში' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'aiko-tm-120t-el' SET pd.meta_description = 'სეიფი Aiko TM.120T EL — ელექტრონული კოდით, 132 ლ + 13 ლ შიდა განყოფილება, 120×44×35.5 სმ, 52 კგ, 5 მმ წინა პანელი. ოფისისთვის. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'aiko-tm-25-el' SET pd.meta_description = 'სეიფი Aiko TM.25 EL — ელექტრონული კოდით, 5 მმ წინა პანელი, 19 ლ, 25×34×28 სმ, 12 კგ. გაძლიერებული დაცვა სახლისა და ოფისისთვის. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'aiko-tm-63t-el' SET pd.meta_description = 'სეიფი Aiko TM.63T EL — ელექტრონული კოდით, 5 მმ წინა პანელი, 34 ლ, 2 განყოფილება, 63×44×35.5 სმ, 34 კგ. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება მთელ საქართველოში' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'aiko-filin-32' SET pd.meta_description = 'იარაღის სეიფი Aiko Filin 32 — 140 სმ სიმაღლე, 3 მმ ფოლადი, 101 ლ + 7 ლ შიდა განყოფილება, 2 გასაღების საკეტი, 64 კგ. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'aiko-chirok-1015' SET pd.meta_description = 'იარაღის სეიფი Aiko Chirok 1015 — 100 სმ სიმაღლე, იარაღი 86 სმ-მდე, 33 ლ, 2 თარო, 2 გასაღების საკეტი, 6 კგ. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება მთელ საქართველოში' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'aiko-key-20' SET pd.meta_description = 'გასაღების შესანახი კარადა Aiko Key-20 — 20 გასაღებისთვის, საკეტით, ფოლადი, კედელზე დასამაგრებელი. ოფისისა და სასტუმროსთვის. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'aiko-key-60' SET pd.meta_description = 'გასაღების შესანახი კარადა Aiko KEY-60 — 60 გასაღებისთვის, ლითონის კაუჭებით, 40×35.5×5.9 სმ, ფოლადი. ოფისისა და სასტუმროსთვის. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = '420ea-20x42x35' SET pd.meta_description = 'სეიფი 420EA — ელექტრონული 8-ნიშნა კოდით და ავარიული გასაღებით, 20×42×35 სმ, კედელზე დასამაგრებელი. საბუთებისა და ძვირფასეულობისთვის. ✓ ნაწილ-ნაწილ გადახდა' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = '17e-17x23x17' SET pd.meta_description = 'მინი სეიფი 17E — ელექტრონული 8-ნიშნა კოდით და ავარიული გასაღებით, 17×23×17 სმ. ფულისა და სამკაულისთვის სახლსა და სასტუმროში. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'mdtb-vega-33-e' SET pd.meta_description = 'სეიფი MDTB-VEGA 33 E — კოდური ელექტრონული საკეტი, ფოლადის კორპუსი, 33.8×41×17.5 სმ. საიმედო დაცვა საბუთებისა და ფასეულობისთვის. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'valberg-frs-73-t-kl-73-2x48-5x43' SET pd.meta_description = 'ცეცხლგამძლე სეიფი Valberg FRS-73.T-KL — ხანძრისგან დაცვა მინ. 1 საათი, 49 ლ + 8 ლ განყოფილება საკეტით, გასაღებით, 86 კგ. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'valberg-frs-36-kl-36x48x43' SET pd.meta_description = 'ცეცხლგამძლე სეიფი Valberg FRS-36.KL — საბუთების დაცვა ხანძრისგან მინ. 1 საათი, 28 ლ, გასაღებით, 36×48×43 სმ, 48 კგ. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'valberg-frs-36-el-36x48x43' SET pd.meta_description = 'ცეცხლგამძლე სეიფი Valberg FRS-36.EL — კლასი 60B, ელექტრონული კოდი + გასაღები, 28 ლ, 36×48×43 სმ, 48 კგ. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება მთელ საქართველოში' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'valberg-frs-30-el-30x40-5x35-5' SET pd.meta_description = 'ცეცხლგამძლე სეიფი Valberg FRS-30.EL — ხანძრისგან დაცვა მინ. 1 საათი, ელექტრონული კოდი + გასაღები, 13 ლ, 28 კგ. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'aiko-chirok-1020-100x30x20' SET pd.meta_description = 'იარაღის სეიფი Aiko Chirok 1020 — 2 თოფისთვის (97 სმ-მდე), ვაზნების განყოფილება საკეტით, 48 ლ, 100×30×20 სმ, 15 კგ. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'valberg-frs-30-kl-30x40-5x35-5' SET pd.meta_description = 'ცეცხლგამძლე სეიფი Valberg FRS-30.KL — კლასი 60B, გასაღებით, 13 ლ, 30×40.5×35.5 სმ, 28 კგ. საბუთებისთვის სახლსა და ოფისში. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'mn1' SET pd.meta_description = 'მინი სეიფი MN1 — კომპაქტური, 23×17×17 სმ, შენადნობი ფოლადი და ქრომი, შიგნით რბილი თექა. ფულისა და სამკაულისთვის. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'fd20-31x29x20' SET pd.meta_description = 'სეიფი FD20 დიდი — ფოლადის, თეთრი, 31×29×20 სმ. საბუთების, ფულისა და ძვირფასეულობის შესანახად სახლსა და ოფისში. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'aiko-chirok-1318' SET pd.meta_description = 'იარაღის სეიფი AIKO Chirok 1318 — 1 თოფისთვის, ზედა განყოფილება ვაზნებისა და პისტოლეტისთვის, 130×26.3×18.3 სმ, გასაღებით. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'aiko-chirok-1320' SET pd.meta_description = 'იარაღის სეიფი AIKO Chirok 1320 — 2 თოფისთვის, 2 დამატებითი განყოფილება ვაზნებისა და აქსესუარებისთვის, 133×30×30 სმ, 16.9 კგ. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'aiko-sl-125t' SET pd.meta_description = 'სეიფი-კარადა Aiko SL-125T — 125 სმ სიმაღლე, 2 თარო, 2 გასაღების საკეტი, ფოლადი. საბუთებისა და ნივთებისთვის ოფისში. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'aiko-chirok-1400x620x300' SET pd.meta_description = 'იარაღის სეიფი Aiko Chirok — 140×62×30 სმ, 3 თარო, 2 გასაღების საკეტი, ფოლადი. იარაღისა და საბრძოლო მასალის შესანახად. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = '170x230x170-17ef' SET pd.meta_description = 'მინი სეიფი 17EF — 17×23×17 სმ, ფოლადი, შავი/ნაცრისფერი. კომპაქტური სეიფი ფულისა და სამკაულისთვის სახლსა და სასტუმროში. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'aiko-sl-87t' SET pd.meta_description = 'სეიფი-კარადა Aiko SL-87T — 87 სმ სიმაღლე, თაროთი, 2 გასაღების საკეტი, ფოლადი. საბუთებისა და ნივთებისთვის ოფისში. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = '170x230x170-17ck' SET pd.meta_description = 'მინი სეიფი 17CK — გასაღებით, 17×23×17 სმ, ფოლადი, შავი/კრემისფერი. ფულისა და სამკაულის შესანახად. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება მთელ საქართველოში' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = '250x350x250-25scl' SET pd.meta_description = 'სეიფი 25SCL — გასაღებით, 25×35×25 სმ, ფოლადი, შავი. საბუთების, ფულისა და ძვირფასეულობისთვის სახლსა და ოფისში. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება მთელ საქართველოში' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = '115x85x40-12k-3' SET pd.meta_description = 'გასაღების შესანახი სეიფი კოდით 12K-3 — 11.5×8.5×4 სმ, ფოლადი, კარზე ან კედელზე დასამაგრებელი. სახლის, ბინისა და ოფისისთვის. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'gn-safe' SET pd.meta_description = 'სეიფი GN-safe — 140 სმ სიმაღლე, 30×28 სმ, ფოლადის, შავი. მაღალი სეიფი გრძელი ნივთების, მათ შორის იარაღის, შესანახად. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = '1541' SET pd.meta_description = 'სეიფი 1541 — ფოლადის, შავი, 35.5×41×15 სმ. ბრტყელი სეიფი საბუთების, ფულისა და ძვირფასეულობის შესანახად. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება მთელ საქართველოში' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'f400-group-limited' SET pd.meta_description = 'სეიფი F400 GROUP LIMITED — მაღალი ხარისხის ფოლადი, 42×45×40 სმ. ფასიანი ნივთებისა და დოკუმენტების საიმედო დაცვა. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = '20sce-200x310x200' SET pd.meta_description = 'სეიფი 20SCE — ფოლადის, შავი, 20×31×20 სმ. კომპაქტური სეიფი საბუთების, ფულისა და სამკაულისთვის. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება მთელ საქართველოში' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'f0901s-200x310x200' SET pd.meta_description = 'სეიფი F0901S — 2 გასაღებით, ფოლადის, შავი, 20×31×20 სმ. საბუთებისა და ფასეულობისთვის სახლსა და ოფისში. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება მთელ საქართველოში' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'filin-35-1390x424x219' SET pd.meta_description = 'იარაღის სეიფი Filin 35 — 170 სმ სიმაღლე, შიდა 139×42.4×21.9 სმ, ფოლადი, 6 გასაღები. იარაღისა და საბრძოლო მასალისთვის. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = '25x8-5x20' SET pd.meta_description = 'მინი სეიფი 25×8.5×20 სმ — კომპაქტური, შენადნობი ფოლადი, 2 გასაღებით, შავი/წითელი. ფულისა და სამკაულისთვის სახლსა და ოფისში. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = '15x8x12' SET pd.meta_description = 'მინი სეიფი 15×8×12 სმ — კომპაქტური, შენადნობი ფოლადი, 2 გასაღებით, ლურჯი/წითელი. ფულისა და სამკაულისთვის. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება მთელ საქართველოში' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = '30x9x24-5' SET pd.meta_description = 'მინი სეიფი 30×9×24.5 სმ — შენადნობი ფოლადი, 2 გასაღებით, ლურჯი/წითელი. ფულის, სამკაულისა და მცირე ფასეულობებისთვის. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = 'safewell-30sav-300x380x300-mm-11' SET pd.meta_description = 'ელექტრონული სეიფი Safewell 30SAV — 3–8 ნიშნა კოდი, სათადარიგო გასაღები, ავტომატური დაბლოკვა, 30×38×30 სმ, 11 კგ. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = '22x35x27-masterlock' SET pd.meta_description = 'ციფრული სეიფი MasterLock 22×35×27 სმ — კოდი + 2 გასაღები, ფოლადი, ბატარეაზე. ძვირფასეულობის, საბუთებისა და ელექტრონიკისთვის. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = '19-4x29x26-4-masterlock' SET pd.meta_description = 'ციფრული სეიფი MasterLock 19.4×29×26.4 სმ — კოდი + 2 გასაღები, ფოლადი, ბატარეაზე. ძვირფასეულობისა და საბუთებისთვის. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება' WHERE pd.lang_code = 'ka';
UPDATE cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 AND s.name = '18x43x37-masterlock' SET pd.meta_description = 'ციფრული სეიფი MasterLock 18×43×37 სმ — კოდი + 2 გასაღები, ფოლადი, შიდა 42.6×17.6×29.4 სმ. საბუთებისა და ელექტრონიკისთვის. ✓ ნაწილ-ნაწილ გადახდა ✓ მიწოდება' WHERE pd.lang_code = 'ka';

-- შემოწმება: 48 ხაზი, ყველას უნდა ჰქონდეს meta_description
SELECT s.name, CHAR_LENGTH(pd.meta_description) AS chars, pd.meta_description FROM cscart_product_descriptions pd JOIN cscart_seo_names s ON s.object_id = pd.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 WHERE pd.lang_code = 'ka' AND s.name IN ('aiko-chirok-1312', 'aiko-t-140-el', 'aiko-t-140-kl', 'aiko-t-17', 'aiko-t-17-el', 'aiko-t-230-el', 'aiko-t-280-el', 'aiko-t-280-kl', 'aiko-tm-120t-el', 'aiko-tm-25-el', 'aiko-tm-63t-el', 'aiko-filin-32', 'aiko-chirok-1015', 'aiko-key-20', 'aiko-key-60', '420ea-20x42x35', '17e-17x23x17', 'mdtb-vega-33-e', 'valberg-frs-73-t-kl-73-2x48-5x43', 'valberg-frs-36-kl-36x48x43', 'valberg-frs-36-el-36x48x43', 'valberg-frs-30-el-30x40-5x35-5', 'aiko-chirok-1020-100x30x20', 'valberg-frs-30-kl-30x40-5x35-5', 'mn1', 'fd20-31x29x20', 'aiko-chirok-1318', 'aiko-chirok-1320', 'aiko-sl-125t', 'aiko-chirok-1400x620x300', '170x230x170-17ef', 'aiko-sl-87t', '170x230x170-17ck', '250x350x250-25scl', '115x85x40-12k-3', 'gn-safe', '1541', 'f400-group-limited', '20sce-200x310x200', 'f0901s-200x310x200', 'filin-35-1390x424x219', '25x8-5x20', '15x8x12', '30x9x24-5', 'safewell-30sav-300x380x300-mm-11', '22x35x27-masterlock', '19-4x29x26-4-masterlock', '18x43x37-masterlock') ORDER BY s.name;

-- დაბრუნება (კომენტარია, არ სრულდება):
-- UPDATE cscart_product_descriptions pd JOIN superi_bk_meta_37 b ON b.product_id = pd.product_id AND b.lang_code = pd.lang_code SET pd.meta_description = b.meta_description;
