-- ============================================================================
-- superi.ge — 41b: შემოწმება (არაფერს ცვლის, მხოლოდ კითხულობს)
-- გაუშვით phpMyAdmin-ის „SQL“ ჩანართში (არა Import-ით) და შედეგის სქრინი გამომიგზავნეთ.
-- რას ვამოწმებთ: რატომ არ ხვდება sitemap-ში
--   • 57 პროდუქტი, რომელიც საიტზე „მარაგშია“ (Samsung Galaxy S26 FE, A37, Z Fold 8, Redmi Note 17 …);
--   • კატეგორიები: სეიფები, სილამაზე და მოვლა, თმის ფენები, ვიდეო ბარათები (შედარებისთვის: გაზქურები, ქურის ზედაპირი);
--   • 6 ბლოგ-სტატია (შედარებისთვის: ის 4, რომელიც sitemap-შია).
-- ============================================================================
SELECT 'product' AS kind, p.product_id AS id, CONVERT(s.name USING utf8mb4) COLLATE utf8mb4_unicode_ci AS slug, CONVERT(pd.product USING utf8mb4) COLLATE utf8mb4_unicode_ci AS name, CONVERT(p.status USING utf8mb4) COLLATE utf8mb4_unicode_ci AS status, CONVERT(CONCAT('amount=', p.amount, ' usergroups=', IFNULL(p.usergroup_ids, '')) USING utf8mb4) COLLATE utf8mb4_unicode_ci AS info
FROM cscart_products p JOIN cscart_seo_names s ON s.object_id = p.product_id AND s.type = 'p' AND s.lang_code = 'ka' AND s.company_id = 1 LEFT JOIN cscart_product_descriptions pd ON pd.product_id = p.product_id AND pd.lang_code = 'ka'
WHERE s.name IN ('50x50x48cm-zt-528', 'acer-aspire-15-15-6-a15-61m-nx-jdher-001-steel', 'automatic-coffee-maker-delonghi-ecam470-85-mb-eletta-ultra', 'bosch-sms6emw38q-13pcs', 'dishwasher-toshiba-dw-10b3-b-cis-bi-81-5x44-8x55-prog-8-set-10-silver', 'electrolux-ena7te75s-bi', 'google-pixel-4-nfc-6gb-64gb-clearly-white', 'gorenje-th60e3b-black', 'gorenje-venus70', 'honor-x7e-6-128gb-black', 'honor-x7e-6-128gb-blue', 'hyundai-hcb-c4405-1900w', 'janome-artdecor-724d', 'korkmaz-a1371-cookware-set-7-pcs', 'lenovo-thinkpad-e16-gen-3-16-21sr004tgx-black', 'lg-gr-c342slbb', 'lg-rh10x56venp-aebqme3-dryer-10kg-black', 'lg-rh80t2sp7rm-adspmea-8', 'lux-garden-sf7a105-400mm-1800w', 'midea-mwh50-20mfg-cis-w-50', 'ninja-jc100eu', 'oneplus-15-5g-12-256gb-black', 'samsung-galaxy-a07s-a077fd-4g-4-128gb-black', 'samsung-galaxy-a07s-a077fd-4g-4-128gb-green', 'samsung-galaxy-a07s-a077fd-4g-4-128gb-violet', 'samsung-galaxy-a14-4gb-64gb-black', 'samsung-galaxy-a27-a276b-ds-5g-6-128gb-pink', 'samsung-galaxy-a27-a276b-ds-5g-8-256gb-black', 'samsung-galaxy-a37-a376ed-5g-6-128gb-black', 'samsung-galaxy-a37-a376ed-5g-8-128gb-light-violet', 'samsung-galaxy-a54-5g-a546e-6gb-128gb-black', 'samsung-galaxy-s26-fe-s741b-ds-5g-8-128gb-jet-black', 'samsung-galaxy-z-flip-8-f776-5g-12-512gb-graphite', 'samsung-galaxy-z-fold-8-12gb-512gb-graphite', 'samsung-galaxy-z-fold-8-ultra-12gb-256gb-graphite-clone', 'samsung-rt42cb662022wt-bespoke', 'samsung-ue85m70hauxpy-85-214', 'samsung-wd80t554cbx-lp', 'samsung-ww11cb944cghlp-11kg', 'samsung-ww11cgp44csblp-11-kg', 'samsung-ww80ag6l28bblp', 'samsung-ww80ag6l28welp-8-kg', 'sony-k-85xr50-85-189', 'tolsen-tol2297-79988-inverter-3-5kw', 'ugreen-pb532-55989b-20000mah-type-c-usb-fast-charging-power-bank-grey', 'xiaomi-poco-c95-pro-6-128gb-lte-global-version-green-clone', 'xiaomi-poco-c95-pro-8-256gb-lte-global-version-blue', 'xiaomi-poco-m8-pro-nfc-5g-12-512gb-black', 'xiaomi-redmi-15c-lte-6gb-128gb-midnight-black', 'xiaomi-redmi-note-17-4g-4-128gb-purple', 'xiaomi-redmi-note-17-4g-6-128gb-teal', 'xiaomi-redmi-note-17-4g-6-256gb-purple', 'xiaomi-redmi-note-17-4g-8-256gb-black', 'xiaomi-redmi-note-17-nfc-5g-6-256gb-purple', 'xiaomi-redmi-pad-2-4-56gb-wi-fi-global-version-purple-clone', 'xiaomi-redmi-pad-2-6-128gb-wi-fi-global-version-green', 'zilan-zln3963')
UNION ALL
SELECT 'category', c.category_id, CONVERT(s.name USING utf8mb4) COLLATE utf8mb4_unicode_ci, CONVERT(cd.category USING utf8mb4) COLLATE utf8mb4_unicode_ci, CONVERT(c.status USING utf8mb4) COLLATE utf8mb4_unicode_ci, CONVERT(CONCAT('parent=', c.parent_id, ' usergroups=', IFNULL(c.usergroup_ids, ''), ' company=', c.company_id) USING utf8mb4) COLLATE utf8mb4_unicode_ci
FROM cscart_categories c JOIN cscart_seo_names s ON s.object_id = c.category_id AND s.type = 'c' AND s.lang_code = 'ka' AND s.company_id = 1 LEFT JOIN cscart_category_descriptions cd ON cd.category_id = c.category_id AND cd.lang_code = 'ka'
WHERE s.name IN ('seifebi', 'silamaze-da-movla', 'tmis-fenebi', 'graphics-cards', 'gazqurebi', 'quris-zedapiri')
UNION ALL
SELECT 'page', pg.page_id, CONVERT(s.name USING utf8mb4) COLLATE utf8mb4_unicode_ci, CONVERT(pgd.page USING utf8mb4) COLLATE utf8mb4_unicode_ci, CONVERT(pg.status USING utf8mb4) COLLATE utf8mb4_unicode_ci, CONVERT(CONCAT('type=', pg.page_type, ' parent=', pg.parent_id, ' usergroups=', IFNULL(pg.usergroup_ids, ''), ' company=', pg.company_id, ' date=', FROM_UNIXTIME(pg.timestamp)) USING utf8mb4) COLLATE utf8mb4_unicode_ci
FROM cscart_pages pg JOIN cscart_seo_names s ON s.object_id = pg.page_id AND s.type NOT IN ('p', 'c') AND s.lang_code = 'ka' LEFT JOIN cscart_page_descriptions pgd ON pgd.page_id = pg.page_id AND pgd.lang_code = 'ka'
WHERE s.name IN ('blog', 'oled-vs-qled-vs-miniled-2026', 'rogor-avirchiot-noutbuqi-2026', 'rogor-shevarchiot-gazis-gamatbobeli', 'rogor-shevarchiot-sarbeni-biliki', 'rogor-shevarchiot-aerogrili', 'rogor-shevarchiot-eleqtro-gamatbobeli', 'rogor-shevarchiot-generatori', 'rogor-shevarchiot-nadzvis-khe', 'rogor-shevarchiot-sakeravi-manqana', 'rogor-shevarchiot-saretskhi-manqana')
ORDER BY kind, status, slug;
